"""billing module + expense doc_type (Wave 2 foundation)

Revision ID: 093406be5044
Revises: 6bb6cbb06e4c
Create Date: 2026-08-20 22:40:33.277671
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '093406be5044'
down_revision: str | None = '6bb6cbb06e4c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_advance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['project_client.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_advance_client_id'), 'billing_advance', ['client_id'], unique=False)
    op.create_index(op.f('ix_billing_advance_po_id'), 'billing_advance', ['po_id'], unique=False)
    op.create_table('billing_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=120), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=True),
    sa.Column('buyer_gstin', sa.String(length=15), nullable=True),
    sa.Column('total_taxable_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_cgst_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_sgst_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_igst_paise', sa.BigInteger(), nullable=True),
    sa.Column('round_off_paise', sa.BigInteger(), nullable=True),
    sa.Column('grand_total_paise', sa.BigInteger(), nullable=True),
    sa.Column('source_engine', sa.String(length=32), nullable=True),
    sa.Column('needs_ocr', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('UPLOADED','EXTRACTED','NEEDS_REVIEW','NEEDS_OCR','NEEDS_MATCH','MATCHED','CONFIRMED','REJECTED','CANCELLED')", name='ck_billing_invoice_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['billing_batch.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['project_client.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['files_stored_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'invoice_number', name='uq_billing_invoice_client_number'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_index(op.f('ix_billing_invoice_batch_id'), 'billing_invoice', ['batch_id'], unique=False)
    op.create_index(op.f('ix_billing_invoice_client_id'), 'billing_invoice', ['client_id'], unique=False)
    op.create_index(op.f('ix_billing_invoice_content_hash'), 'billing_invoice', ['content_hash'], unique=False)
    op.create_index(op.f('ix_billing_invoice_invoice_number'), 'billing_invoice', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_billing_invoice_po_id'), 'billing_invoice', ['po_id'], unique=False)
    op.create_index(op.f('ix_billing_invoice_source_file_id'), 'billing_invoice', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_billing_invoice_status'), 'billing_invoice', ['status'], unique=False)
    op.create_table('billing_advance_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advance_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['advance_id'], ['billing_advance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_advance_application_advance_id'), 'billing_advance_application', ['advance_id'], unique=False)
    op.create_index(op.f('ix_billing_advance_application_invoice_id'), 'billing_advance_application', ['invoice_id'], unique=False)
    op.create_table('billing_credit_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('cn_number', sa.String(length=120), nullable=False),
    sa.Column('cn_date', sa.Date(), nullable=True),
    sa.Column('total_taxable_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_cgst_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_sgst_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_igst_paise', sa.BigInteger(), nullable=True),
    sa.Column('round_off_paise', sa.BigInteger(), nullable=True),
    sa.Column('grand_total_paise', sa.BigInteger(), nullable=True),
    sa.Column('source_engine', sa.String(length=32), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('UPLOADED','EXTRACTED','NEEDS_REVIEW','NEEDS_OCR','NEEDS_MATCH','MATCHED','CONFIRMED','REJECTED','CANCELLED')", name='ck_billing_cn_status'),
    sa.ForeignKeyConstraint(['client_id'], ['project_client.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoice.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['files_stored_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'cn_number', name='uq_billing_cn_client_number'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_index(op.f('ix_billing_credit_note_client_id'), 'billing_credit_note', ['client_id'], unique=False)
    op.create_index(op.f('ix_billing_credit_note_cn_number'), 'billing_credit_note', ['cn_number'], unique=False)
    op.create_index(op.f('ix_billing_credit_note_content_hash'), 'billing_credit_note', ['content_hash'], unique=False)
    op.create_index(op.f('ix_billing_credit_note_invoice_id'), 'billing_credit_note', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_billing_credit_note_source_file_id'), 'billing_credit_note', ['source_file_id'], unique=False)
    op.create_table('billing_invoice_correction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.String(length=500), nullable=True),
    sa.Column('new_value', sa.String(length=500), nullable=True),
    sa.Column('promoted_to_gold', sa.Boolean(), nullable=False),
    sa.Column('actor_uid', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoice_correction_invoice_id'), 'billing_invoice_correction', ['invoice_id'], unique=False)
    op.create_table('billing_invoice_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(length=64), nullable=False),
    sa.Column('value_raw', sa.String(length=500), nullable=True),
    sa.Column('value_norm', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_engine', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'field_path', name='uq_billing_invoice_field')
    )
    op.create_index(op.f('ix_billing_invoice_field_invoice_id'), 'billing_invoice_field', ['invoice_id'], unique=False)
    op.create_table('billing_invoice_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('po_line_item_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('hsn_sac', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_rate_paise', sa.BigInteger(), nullable=True),
    sa.Column('taxable_paise', sa.BigInteger(), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgst_paise', sa.BigInteger(), nullable=True),
    sa.Column('sgst_paise', sa.BigInteger(), nullable=True),
    sa.Column('igst_paise', sa.BigInteger(), nullable=True),
    sa.Column('line_total_paise', sa.BigInteger(), nullable=True),
    sa.Column('match_status', sa.String(length=12), nullable=False),
    sa.CheckConstraint("match_status in ('UNMATCHED','MATCHED','MANUAL')", name='ck_billing_line_match'),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_line_item_id'], ['po_line_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoice_line_invoice_id'), 'billing_invoice_line', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_billing_invoice_line_po_line_item_id'), 'billing_invoice_line', ['po_line_item_id'], unique=False)
    op.create_table('billing_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['project_client.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_payment_client_id'), 'billing_payment', ['client_id'], unique=False)
    op.create_index(op.f('ix_billing_payment_invoice_id'), 'billing_payment', ['invoice_id'], unique=False)
    op.create_table('billing_credit_note_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('po_line_item_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('taxable_paise', sa.BigInteger(), nullable=True),
    sa.Column('line_total_paise', sa.BigInteger(), nullable=True),
    sa.Column('match_status', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['cn_id'], ['billing_credit_note.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_line_item_id'], ['po_line_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_credit_note_line_cn_id'), 'billing_credit_note_line', ['cn_id'], unique=False)
    op.create_index(op.f('ix_billing_credit_note_line_po_line_item_id'), 'billing_credit_note_line', ['po_line_item_id'], unique=False)
    # Batch mode so SQLite can add the columns + a self-referential FK; doc_type is NOT
    # NULL with server_default 'INVOICE' so every existing row backfills to an invoice
    # (server_default isn't compared by `alembic check`, so no drift). On Postgres batch
    # emits plain ALTERs.
    with op.batch_alter_table('expense_invoice') as batch:
        batch.add_column(sa.Column('doc_type', sa.String(length=16), nullable=False,
                                   server_default='INVOICE'))
        batch.add_column(sa.Column('against_invoice_id', sa.Integer(), nullable=True))
        batch.create_index(batch.f('ix_expense_invoice_against_invoice_id'),
                           ['against_invoice_id'], unique=False)
        batch.create_index(batch.f('ix_expense_invoice_doc_type'), ['doc_type'], unique=False)
        batch.create_foreign_key('fk_expense_invoice_against_invoice', 'expense_invoice',
                                 ['against_invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_invoice') as batch:
        batch.drop_constraint('fk_expense_invoice_against_invoice', type_='foreignkey')
        batch.drop_index(batch.f('ix_expense_invoice_doc_type'))
        batch.drop_index(batch.f('ix_expense_invoice_against_invoice_id'))
        batch.drop_column('against_invoice_id')
        batch.drop_column('doc_type')
    op.drop_index(op.f('ix_billing_credit_note_line_po_line_item_id'), table_name='billing_credit_note_line')
    op.drop_index(op.f('ix_billing_credit_note_line_cn_id'), table_name='billing_credit_note_line')
    op.drop_table('billing_credit_note_line')
    op.drop_index(op.f('ix_billing_payment_invoice_id'), table_name='billing_payment')
    op.drop_index(op.f('ix_billing_payment_client_id'), table_name='billing_payment')
    op.drop_table('billing_payment')
    op.drop_index(op.f('ix_billing_invoice_line_po_line_item_id'), table_name='billing_invoice_line')
    op.drop_index(op.f('ix_billing_invoice_line_invoice_id'), table_name='billing_invoice_line')
    op.drop_table('billing_invoice_line')
    op.drop_index(op.f('ix_billing_invoice_field_invoice_id'), table_name='billing_invoice_field')
    op.drop_table('billing_invoice_field')
    op.drop_index(op.f('ix_billing_invoice_correction_invoice_id'), table_name='billing_invoice_correction')
    op.drop_table('billing_invoice_correction')
    op.drop_index(op.f('ix_billing_credit_note_source_file_id'), table_name='billing_credit_note')
    op.drop_index(op.f('ix_billing_credit_note_invoice_id'), table_name='billing_credit_note')
    op.drop_index(op.f('ix_billing_credit_note_content_hash'), table_name='billing_credit_note')
    op.drop_index(op.f('ix_billing_credit_note_cn_number'), table_name='billing_credit_note')
    op.drop_index(op.f('ix_billing_credit_note_client_id'), table_name='billing_credit_note')
    op.drop_table('billing_credit_note')
    op.drop_index(op.f('ix_billing_advance_application_invoice_id'), table_name='billing_advance_application')
    op.drop_index(op.f('ix_billing_advance_application_advance_id'), table_name='billing_advance_application')
    op.drop_table('billing_advance_application')
    op.drop_index(op.f('ix_billing_invoice_status'), table_name='billing_invoice')
    op.drop_index(op.f('ix_billing_invoice_source_file_id'), table_name='billing_invoice')
    op.drop_index(op.f('ix_billing_invoice_po_id'), table_name='billing_invoice')
    op.drop_index(op.f('ix_billing_invoice_invoice_number'), table_name='billing_invoice')
    op.drop_index(op.f('ix_billing_invoice_content_hash'), table_name='billing_invoice')
    op.drop_index(op.f('ix_billing_invoice_client_id'), table_name='billing_invoice')
    op.drop_index(op.f('ix_billing_invoice_batch_id'), table_name='billing_invoice')
    op.drop_table('billing_invoice')
    op.drop_index(op.f('ix_billing_advance_po_id'), table_name='billing_advance')
    op.drop_index(op.f('ix_billing_advance_client_id'), table_name='billing_advance')
    op.drop_table('billing_advance')
    op.drop_table('billing_batch')
    # ### end Alembic commands ###
