"""one-default partial unique indexes (L1) + client child

Revision ID: 15c87b87e5af
Revises: 093406be5044
Create Date: 2026-08-21 08:30:36.881261
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '15c87b87e5af'
down_revision: str | None = '093406be5044'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_client_address_one_default', 'client_address', ['client_id'], unique=True, sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default'))
    op.create_index('uq_client_contact_one_default', 'client_contact', ['client_id'], unique=True, sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default'))
    op.create_index('uq_client_gstin_one_default', 'client_gstin', ['client_id'], unique=True, sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_client_gstin_one_default', table_name='client_gstin', sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default'))
    op.drop_index('uq_client_contact_one_default', table_name='client_contact', sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default'))
    op.drop_index('uq_client_address_one_default', table_name='client_address', sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default'))
    # ### end Alembic commands ###
