"""challan register indexes

Revision ID: 1e2c7d8a41d7
Revises: 6598f029a98e
Create Date: 2026-08-18 18:54:24.924406
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1e2c7d8a41d7'
down_revision: str | None = '6598f029a98e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_challan_challan_date'), 'challan', ['challan_date'], unique=False)
    op.create_index('ix_challan_consignee_gstin_challan_date', 'challan', ['consignee_gstin', 'challan_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_challan_consignee_gstin_challan_date', table_name='challan')
    op.drop_index(op.f('ix_challan_challan_date'), table_name='challan')
    # ### end Alembic commands ###
