"""master data + challan tables

Revision ID: 52edd5ff2830
Revises: ad8a9c93c1ac
Create Date: 2026-08-11 12:02:01.238459
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '52edd5ff2830'
down_revision: str | None = 'ad8a9c93c1ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_consignee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=600), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'state', name='uq_md_consignee_brand_state')
    )
    op.create_index(op.f('ix_md_consignee_brand'), 'md_consignee', ['brand'], unique=False)
    op.create_index(op.f('ix_md_consignee_state'), 'md_consignee', ['state'], unique=False)
    # HAND-ADDED: case-insensitive uniqueness so "Deoleo"/"deoleo"/"Deoleo " can't
    # both persist -> consignee resolution (and the GSTIN it snapshots) stays unambiguous.
    op.create_index(
        'uq_md_consignee_brand_state_ci', 'md_consignee',
        [sa.text('lower(trim(brand))'), sa.text('lower(trim(state))')], unique=True,
    )
    op.create_table('md_consignor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=600), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_md_consignor_gstin'), 'md_consignor', ['gstin'], unique=False)
    op.create_index(op.f('ix_md_consignor_name'), 'md_consignor', ['name'], unique=False)
    op.create_table('md_hsn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hsn', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_md_hsn_hsn'), 'md_hsn', ['hsn'], unique=True)
    op.create_table('md_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_md_series_letter'), 'md_series', ['letter'], unique=True)
    op.create_table('challan_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error_report_file_id', sa.Integer(), nullable=True),
    sa.Column('zip_file_id', sa.Integer(), nullable=True),
    sa.Column('merged_pdf_file_id', sa.Integer(), nullable=True),
    sa.Column('challan_count', sa.Integer(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['error_report_file_id'], ['files_stored_file.id'], ),
    sa.ForeignKeyConstraint(['merged_pdf_file_id'], ['files_stored_file.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['files_stored_file.id'], ),
    sa.ForeignKeyConstraint(['zip_file_id'], ['files_stored_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challan_batch_created_by'), 'challan_batch', ['created_by'], unique=False)
    op.create_index(op.f('ix_challan_batch_status'), 'challan_batch', ['status'], unique=False)
    op.create_table('challan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('series', sa.String(length=8), nullable=False),
    sa.Column('fy', sa.String(length=7), nullable=False),
    sa.Column('number_int', sa.Integer(), nullable=False),
    sa.Column('challan_date', sa.Date(), nullable=False),
    sa.Column('consignor_name', sa.String(length=200), nullable=False),
    sa.Column('consignor_gstin', sa.String(length=15), nullable=False),
    sa.Column('consignor_state', sa.String(length=60), nullable=False),
    sa.Column('consignor_address', sa.String(length=600), nullable=False),
    sa.Column('consignor_phone', sa.String(length=40), nullable=False),
    sa.Column('consignee_brand', sa.String(length=120), nullable=False),
    sa.Column('consignee_name', sa.String(length=200), nullable=False),
    sa.Column('consignee_gstin', sa.String(length=15), nullable=False),
    sa.Column('consignee_state', sa.String(length=60), nullable=False),
    sa.Column('consignee_address', sa.String(length=600), nullable=False),
    sa.Column('consignee_phone', sa.String(length=40), nullable=False),
    sa.Column('ship_to_name', sa.String(length=200), nullable=False),
    sa.Column('ship_to_address', sa.String(length=600), nullable=False),
    sa.Column('ship_to_state', sa.String(length=60), nullable=False),
    sa.Column('ship_to_enterprise', sa.String(length=200), nullable=False),
    sa.Column('ship_to_number', sa.String(length=40), nullable=False),
    sa.Column('ship_to_contact', sa.String(length=200), nullable=False),
    sa.Column('po_number', sa.String(length=60), nullable=False),
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('eway_required', sa.Boolean(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('void_reason', sa.String(length=300), nullable=True),
    sa.Column('pdf_file_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('ISSUED', 'VOID')", name='ck_challan_status'),
    sa.ForeignKeyConstraint(['allocation_id'], ['numbering_allocation.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['challan_batch.id'], ),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['files_stored_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_id')
    )
    op.create_index(op.f('ix_challan_batch_id'), 'challan', ['batch_id'], unique=False)
    op.create_index(op.f('ix_challan_fy'), 'challan', ['fy'], unique=False)
    op.create_index(op.f('ix_challan_number'), 'challan', ['number'], unique=False)
    op.create_index(op.f('ix_challan_status'), 'challan', ['status'], unique=False)
    op.create_table('challan_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challan_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=False),
    sa.Column('hsn', sa.String(length=12), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate_text', sa.String(length=60), nullable=False),
    sa.Column('rate_paise', sa.BigInteger(), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['challan_id'], ['challan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challan_line_item_challan_id'), 'challan_line_item', ['challan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challan_line_item_challan_id'), table_name='challan_line_item')
    op.drop_table('challan_line_item')
    op.drop_index(op.f('ix_challan_status'), table_name='challan')
    op.drop_index(op.f('ix_challan_number'), table_name='challan')
    op.drop_index(op.f('ix_challan_fy'), table_name='challan')
    op.drop_index(op.f('ix_challan_batch_id'), table_name='challan')
    op.drop_table('challan')
    op.drop_index(op.f('ix_challan_batch_status'), table_name='challan_batch')
    op.drop_index(op.f('ix_challan_batch_created_by'), table_name='challan_batch')
    op.drop_table('challan_batch')
    op.drop_index(op.f('ix_md_series_letter'), table_name='md_series')
    op.drop_table('md_series')
    op.drop_index(op.f('ix_md_hsn_hsn'), table_name='md_hsn')
    op.drop_table('md_hsn')
    op.drop_index(op.f('ix_md_consignor_name'), table_name='md_consignor')
    op.drop_index(op.f('ix_md_consignor_gstin'), table_name='md_consignor')
    op.drop_table('md_consignor')
    op.drop_index(op.f('ix_md_consignee_state'), table_name='md_consignee')
    op.drop_index(op.f('ix_md_consignee_brand'), table_name='md_consignee')
    op.drop_table('md_consignee')
    # ### end Alembic commands ###
