"""inc17 challan group_key for resume reconcile

Revision ID: 6598f029a98e
Revises: 8a1ab1024872
Create Date: 2026-08-14 21:17:33.983157
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6598f029a98e'
down_revision: str | None = '8a1ab1024872'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default '' so the ALTER applies cleanly over existing issued-challan rows
    # (they predate resume tracking; their empty group_key just opts them out of it).
    op.add_column(
        'challan',
        sa.Column('group_key', sa.String(length=120), nullable=False, server_default=''),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challan', 'group_key')
    # ### end Alembic commands ###
