"""projects module tables

Revision ID: 690e7736007c
Revises: 52edd5ff2830
Create Date: 2026-08-14 11:56:22.593880
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '690e7736007c'
down_revision: str | None = '52edd5ff2830'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_client_code'), 'project_client', ['code'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('ACTIVE', 'ON_HOLD', 'CLOSED')", name='ck_project_status'),
    sa.ForeignKeyConstraint(['client_id'], ['project_client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'seq', name='uq_project_client_seq')
    )
    op.create_index(op.f('ix_project_client_id'), 'project', ['client_id'], unique=False)
    op.create_index(op.f('ix_project_code'), 'project', ['code'], unique=True)
    op.create_index(op.f('ix_project_status'), 'project', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_status'), table_name='project')
    op.drop_index(op.f('ix_project_code'), table_name='project')
    op.drop_index(op.f('ix_project_client_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_project_client_code'), table_name='project_client')
    op.drop_table('project_client')
    # ### end Alembic commands ###
