"""project spine foundation: client master, product, purchase orders, numbering prefix

Revision ID: 6bb6cbb06e4c
Revises: fccb5f50f5a7
Create Date: 2026-08-20 19:51:52.219631
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6bb6cbb06e4c'
down_revision: str | None = 'fccb5f50f5a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('model_number', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('hsn', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # Case-insensitive product identity (name, brand, model_number) — NULL brand/model
    # coalesced to '' so two rows differing only by case can't both persist and split
    # quote history. Applied by hand (expression indexes aren't autogenerated); mirrors
    # the model's `uq_product_identity` in __table_args__ so `alembic check` agrees.
    op.create_index(
        'uq_product_identity', 'product',
        [sa.text('lower(name)'), sa.text("lower(coalesce(brand, ''))"),
         sa.text("lower(coalesce(model_number, ''))")],
        unique=True,
    )
    op.create_table('client_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['project_client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contact_client_id'), 'client_contact', ['client_id'], unique=False)
    op.create_table('client_gstin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['project_client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'gstin', name='uq_client_gstin')
    )
    op.create_index(op.f('ix_client_gstin_client_id'), 'client_gstin', ['client_id'], unique=False)
    op.create_table('client_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('gstin_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('line1', sa.String(length=300), nullable=False),
    sa.Column('line2', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['project_client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gstin_id'], ['client_gstin.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_address_client_id'), 'client_address', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_address_gstin_id'), 'client_address', ['gstin_id'], unique=False)
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_gstin_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('soft_copy_file_id', sa.Integer(), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('expected_procurement_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('close_reason', sa.String(length=500), nullable=True),
    sa.Column('closed_by', sa.String(length=128), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('DRAFT', 'CONFIRMED', 'IN_PROGRESS', 'CLOSED', 'CANCELLED')", name='ck_purchase_order_status'),
    sa.ForeignKeyConstraint(['client_gstin_id'], ['client_gstin.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['project_client.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['soft_copy_file_id'], ['files_stored_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'po_number', name='uq_purchase_order_client_number')
    )
    op.create_index(op.f('ix_purchase_order_client_gstin_id'), 'purchase_order', ['client_gstin_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_client_id'), 'purchase_order', ['client_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_po_number'), 'purchase_order', ['po_number'], unique=False)
    op.create_index(op.f('ix_purchase_order_project_id'), 'purchase_order', ['project_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_soft_copy_file_id'), 'purchase_order', ['soft_copy_file_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_status'), 'purchase_order', ['status'], unique=False)
    op.create_table('po_amendment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_id', 'version', name='uq_po_amendment_version')
    )
    op.create_index(op.f('ix_po_amendment_po_id'), 'po_amendment', ['po_id'], unique=False)
    op.create_table('po_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('ordered_qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('cost_price_paise', sa.BigInteger(), nullable=False),
    sa.Column('sell_price_paise', sa.BigInteger(), nullable=False),
    sa.Column('freight_paise', sa.BigInteger(), nullable=False),
    sa.Column('packaging_paise', sa.BigInteger(), nullable=False),
    sa.Column('handling_paise', sa.BigInteger(), nullable=False),
    sa.Column('other_paise', sa.BigInteger(), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_status', sa.String(length=16), nullable=False),
    sa.Column('short_closed_qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('short_close_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("line_status in ('OPEN', 'SHORT_CLOSED', 'CLOSED')", name='ck_po_line_status'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_line_item_po_id'), 'po_line_item', ['po_id'], unique=False)
    op.create_index(op.f('ix_po_line_item_product_id'), 'po_line_item', ['product_id'], unique=False)
    # NOT NULL + server_default so the existing challan "L" counter row backfills to
    # "GIF/DC" (SQLite requires a default to add a NOT NULL column to a non-empty table);
    # new invoice/credit-note series seed their own prefix. server_default is not
    # compared by `alembic check` (compare_server_default is off), so no drift.
    op.add_column('numbering_counter',
                  sa.Column('prefix', sa.String(length=16), nullable=False, server_default='GIF/DC'))
    op.add_column('project_client', sa.Column('pan', sa.String(length=10), nullable=True))
    op.add_column('project_client', sa.Column('credit_terms_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_client', 'credit_terms_days')
    op.drop_column('project_client', 'pan')
    op.drop_column('numbering_counter', 'prefix')
    op.drop_index(op.f('ix_po_line_item_product_id'), table_name='po_line_item')
    op.drop_index(op.f('ix_po_line_item_po_id'), table_name='po_line_item')
    op.drop_table('po_line_item')
    op.drop_index(op.f('ix_po_amendment_po_id'), table_name='po_amendment')
    op.drop_table('po_amendment')
    op.drop_index(op.f('ix_purchase_order_status'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_soft_copy_file_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_project_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_po_number'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_client_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_client_gstin_id'), table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_client_address_gstin_id'), table_name='client_address')
    op.drop_index(op.f('ix_client_address_client_id'), table_name='client_address')
    op.drop_table('client_address')
    op.drop_index(op.f('ix_client_gstin_client_id'), table_name='client_gstin')
    op.drop_table('client_gstin')
    op.drop_index(op.f('ix_client_contact_client_id'), table_name='client_contact')
    op.drop_table('client_contact')
    op.drop_index('uq_product_identity', table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
