"""logistics shipment table (Wave 3)

Revision ID: 86fd55b35152
Revises: 15c87b87e5af
Create Date: 2026-08-21 08:52:02.459378
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '86fd55b35152'
down_revision: str | None = '15c87b87e5af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistics_shipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challan_number', sa.String(length=64), nullable=False),
    sa.Column('challan_id', sa.Integer(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('tracking_id', sa.String(length=120), nullable=True),
    sa.Column('delivery_partner', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('consignee_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=600), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('dispatched_on', sa.Date(), nullable=True),
    sa.Column('delivered_on', sa.Date(), nullable=True),
    sa.Column('pod_file_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('PENDING','DISPATCHED','IN_TRANSIT','DELIVERED','RETURNED','FAILED')", name='ck_logistics_shipment_status'),
    sa.ForeignKeyConstraint(['challan_id'], ['challan.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['pod_file_id'], ['files_stored_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challan_number', name='uq_logistics_shipment_challan_number')
    )
    op.create_index(op.f('ix_logistics_shipment_challan_id'), 'logistics_shipment', ['challan_id'], unique=False)
    op.create_index(op.f('ix_logistics_shipment_challan_number'), 'logistics_shipment', ['challan_number'], unique=False)
    op.create_index(op.f('ix_logistics_shipment_po_id'), 'logistics_shipment', ['po_id'], unique=False)
    op.create_index(op.f('ix_logistics_shipment_status'), 'logistics_shipment', ['status'], unique=False)
    op.create_index(op.f('ix_logistics_shipment_tracking_id'), 'logistics_shipment', ['tracking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistics_shipment_tracking_id'), table_name='logistics_shipment')
    op.drop_index(op.f('ix_logistics_shipment_status'), table_name='logistics_shipment')
    op.drop_index(op.f('ix_logistics_shipment_po_id'), table_name='logistics_shipment')
    op.drop_index(op.f('ix_logistics_shipment_challan_number'), table_name='logistics_shipment')
    op.drop_index(op.f('ix_logistics_shipment_challan_id'), table_name='logistics_shipment')
    op.drop_table('logistics_shipment')
    # ### end Alembic commands ###
