"""expense module tables

Revision ID: 88d04b809c75
Revises: 1e2c7d8a41d7
Create Date: 2026-08-19 11:40:04.833735
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '88d04b809c75'
down_revision: str | None = '1e2c7d8a41d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'EXTRACTING', 'COMPLETED', 'FAILED')", name='ck_expense_batch_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_batch_status'), 'expense_batch', ['status'], unique=False)
    op.create_table('expense_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('source_engine', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('needs_ocr', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('supplier_name', sa.String(length=300), nullable=True),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=True),
    sa.Column('supplier_address', sa.String(length=600), nullable=True),
    sa.Column('buyer_name', sa.String(length=300), nullable=True),
    sa.Column('buyer_gstin', sa.String(length=15), nullable=True),
    sa.Column('buyer_address', sa.String(length=600), nullable=True),
    sa.Column('invoice_number', sa.String(length=64), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('place_of_supply', sa.String(length=64), nullable=True),
    sa.Column('po_ref', sa.String(length=64), nullable=True),
    sa.Column('total_taxable_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_cgst_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_sgst_paise', sa.BigInteger(), nullable=True),
    sa.Column('total_igst_paise', sa.BigInteger(), nullable=True),
    sa.Column('round_off_paise', sa.BigInteger(), nullable=True),
    sa.Column('grand_total_paise', sa.BigInteger(), nullable=True),
    sa.Column('amount_in_words', sa.String(length=600), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('UPLOADED', 'EXTRACTED', 'NEEDS_REVIEW', 'NEEDS_OCR', 'CONFIRMED', 'REJECTED')", name='ck_expense_invoice_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['expense_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['files_stored_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_expense_invoice_dedup_key')
    )
    op.create_index(op.f('ix_expense_invoice_batch_id'), 'expense_invoice', ['batch_id'], unique=False)
    op.create_index(op.f('ix_expense_invoice_content_hash'), 'expense_invoice', ['content_hash'], unique=False)
    op.create_index(op.f('ix_expense_invoice_invoice_date'), 'expense_invoice', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_expense_invoice_status'), 'expense_invoice', ['status'], unique=False)
    op.create_index(op.f('ix_expense_invoice_supplier_gstin'), 'expense_invoice', ['supplier_gstin'], unique=False)
    op.create_table('expense_invoice_correction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.String(length=600), nullable=True),
    sa.Column('new_value', sa.String(length=600), nullable=True),
    sa.Column('corrected_by', sa.String(length=128), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('promoted_to_gold', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['expense_invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_invoice_correction_invoice_id'), 'expense_invoice_correction', ['invoice_id'], unique=False)
    op.create_table('expense_invoice_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(length=64), nullable=False),
    sa.Column('value_normalized', sa.String(length=600), nullable=True),
    sa.Column('value_raw', sa.String(length=600), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source_engine', sa.String(length=32), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('OK', 'LOW_CONFIDENCE', 'MISSING', 'CORRECTED')", name='ck_expense_field_status'),
    sa.ForeignKeyConstraint(['invoice_id'], ['expense_invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'field_path', name='uq_expense_field_path')
    )
    op.create_index(op.f('ix_expense_invoice_field_invoice_id'), 'expense_invoice_field', ['invoice_id'], unique=False)
    op.create_table('expense_invoice_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('hsn_sac', sa.String(length=12), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_rate_paise', sa.BigInteger(), nullable=True),
    sa.Column('taxable_paise', sa.BigInteger(), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgst_paise', sa.BigInteger(), nullable=True),
    sa.Column('sgst_paise', sa.BigInteger(), nullable=True),
    sa.Column('igst_paise', sa.BigInteger(), nullable=True),
    sa.Column('line_total_paise', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['expense_invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_invoice_line_invoice_id'), 'expense_invoice_line', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_invoice_line_invoice_id'), table_name='expense_invoice_line')
    op.drop_table('expense_invoice_line')
    op.drop_index(op.f('ix_expense_invoice_field_invoice_id'), table_name='expense_invoice_field')
    op.drop_table('expense_invoice_field')
    op.drop_index(op.f('ix_expense_invoice_correction_invoice_id'), table_name='expense_invoice_correction')
    op.drop_table('expense_invoice_correction')
    op.drop_index(op.f('ix_expense_invoice_supplier_gstin'), table_name='expense_invoice')
    op.drop_index(op.f('ix_expense_invoice_status'), table_name='expense_invoice')
    op.drop_index(op.f('ix_expense_invoice_invoice_date'), table_name='expense_invoice')
    op.drop_index(op.f('ix_expense_invoice_content_hash'), table_name='expense_invoice')
    op.drop_index(op.f('ix_expense_invoice_batch_id'), table_name='expense_invoice')
    op.drop_table('expense_invoice')
    op.drop_index(op.f('ix_expense_batch_status'), table_name='expense_batch')
    op.drop_table('expense_batch')
    # ### end Alembic commands ###
