"""inc16 challan batch decision + needs_review

Revision ID: 8a1ab1024872
Revises: 3dab8e347c22
Create Date: 2026-08-14 20:12:37.485085
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8a1ab1024872'
down_revision: str | None = '3dab8e347c22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challan_batch_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('consignee_name', sa.String(length=200), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('stored_value', sa.String(length=600), nullable=False),
    sa.Column('uploaded_value', sa.String(length=600), nullable=False),
    sa.Column('choice', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("choice in ('PENDING', 'UPDATE_MASTER', 'THIS_UPLOAD', 'REJECT')", name='ck_challan_decision_choice'),
    sa.ForeignKeyConstraint(['batch_id'], ['challan_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'gstin', 'field', name='uq_challan_decision')
    )
    op.create_index(op.f('ix_challan_batch_decision_batch_id'), 'challan_batch_decision', ['batch_id'], unique=False)
    op.create_index(op.f('ix_challan_batch_decision_gstin'), 'challan_batch_decision', ['gstin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challan_batch_decision_gstin'), table_name='challan_batch_decision')
    op.drop_index(op.f('ix_challan_batch_decision_batch_id'), table_name='challan_batch_decision')
    op.drop_table('challan_batch_decision')
    # ### end Alembic commands ###
