"""numbering tables

Revision ID: ad8a9c93c1ac
Revises: e215e02932b5
Create Date: 2026-08-10 11:52:28.159885
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ad8a9c93c1ac'
down_revision: str | None = 'e215e02932b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numbering_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=8), nullable=False),
    sa.Column('fy', sa.String(length=7), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('formatted', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('entity', sa.String(length=120), nullable=True),
    sa.Column('entity_id', sa.String(length=120), nullable=True),
    sa.Column('reserved_by', sa.String(length=128), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=300), nullable=True),
    sa.CheckConstraint("status in ('RESERVED', 'ISSUED', 'VOID')", name='ck_numbering_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_numbering_allocation_formatted'), 'numbering_allocation', ['formatted'], unique=False)
    op.create_index(op.f('ix_numbering_allocation_fy'), 'numbering_allocation', ['fy'], unique=False)
    op.create_index(op.f('ix_numbering_allocation_reserved_at'), 'numbering_allocation', ['reserved_at'], unique=False)
    op.create_index(op.f('ix_numbering_allocation_series'), 'numbering_allocation', ['series'], unique=False)
    op.create_index(op.f('ix_numbering_allocation_status'), 'numbering_allocation', ['status'], unique=False)
    op.create_table('numbering_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=8), nullable=False),
    sa.Column('fy', sa.String(length=7), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series', 'fy', name='uq_numbering_counter')
    )
    op.create_index(op.f('ix_numbering_counter_fy'), 'numbering_counter', ['fy'], unique=False)
    op.create_index(op.f('ix_numbering_counter_series'), 'numbering_counter', ['series'], unique=False)
    # ### end Alembic commands ###

    # --- HAND-ADDED: the statutory duplicate backstop (invariant I1). ---
    # At most ONE active (non-VOID) allocation may exist per (series, fy, number).
    # A partial index (WHERE status <> 'VOID') so a cancelled number's history row
    # never blocks the sequence. `status` is a plain String, so the SAME predicate
    # works on sqlite and Postgres (no Enum cast) — dialect-specific `where` kwargs
    # both carry it. The ORM does not model this; it MUST live here by hand.
    op.create_index(
        "uq_numbering_active",
        "numbering_allocation",
        ["series", "fy", "number"],
        unique=True,
        sqlite_where=sa.text("status <> 'VOID'"),
        postgresql_where=sa.text("status <> 'VOID'"),
    )


def downgrade() -> None:
    op.drop_index("uq_numbering_active", table_name="numbering_allocation")
    op.drop_index(op.f('ix_numbering_counter_series'), table_name='numbering_counter')
    op.drop_index(op.f('ix_numbering_counter_fy'), table_name='numbering_counter')
    op.drop_table('numbering_counter')
    op.drop_index(op.f('ix_numbering_allocation_status'), table_name='numbering_allocation')
    op.drop_index(op.f('ix_numbering_allocation_series'), table_name='numbering_allocation')
    op.drop_index(op.f('ix_numbering_allocation_reserved_at'), table_name='numbering_allocation')
    op.drop_index(op.f('ix_numbering_allocation_fy'), table_name='numbering_allocation')
    op.drop_index(op.f('ix_numbering_allocation_formatted'), table_name='numbering_allocation')
    op.drop_table('numbering_allocation')
    # ### end Alembic commands ###
