"""challan tables

Revision ID: c57f9ac224ca
Revises: e313362febfe
Create Date: 2026-08-10 14:43:03.943406
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c57f9ac224ca'
down_revision: str | None = 'e313362febfe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challan_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error_report_file_id', sa.Integer(), nullable=True),
    sa.Column('zip_file_id', sa.Integer(), nullable=True),
    sa.Column('merged_pdf_file_id', sa.Integer(), nullable=True),
    sa.Column('challan_count', sa.Integer(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['error_report_file_id'], ['files_stored_file.id'], ),
    sa.ForeignKeyConstraint(['merged_pdf_file_id'], ['files_stored_file.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['files_stored_file.id'], ),
    sa.ForeignKeyConstraint(['zip_file_id'], ['files_stored_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challan_batch_created_by'), 'challan_batch', ['created_by'], unique=False)
    op.create_index(op.f('ix_challan_batch_status'), 'challan_batch', ['status'], unique=False)
    op.create_table('challan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('series', sa.String(length=8), nullable=False),
    sa.Column('fy', sa.String(length=7), nullable=False),
    sa.Column('number_int', sa.Integer(), nullable=False),
    sa.Column('challan_date', sa.Date(), nullable=False),
    sa.Column('consignor_name', sa.String(length=200), nullable=False),
    sa.Column('consignor_gstin', sa.String(length=15), nullable=False),
    sa.Column('consignor_state', sa.String(length=60), nullable=False),
    sa.Column('consignor_address', sa.String(length=600), nullable=False),
    sa.Column('consignee_brand', sa.String(length=120), nullable=False),
    sa.Column('consignee_name', sa.String(length=200), nullable=False),
    sa.Column('consignee_gstin', sa.String(length=15), nullable=False),
    sa.Column('consignee_state', sa.String(length=60), nullable=False),
    sa.Column('consignee_address', sa.String(length=600), nullable=False),
    sa.Column('ship_to_name', sa.String(length=200), nullable=False),
    sa.Column('ship_to_address', sa.String(length=600), nullable=False),
    sa.Column('ship_to_state', sa.String(length=60), nullable=False),
    sa.Column('po_number', sa.String(length=60), nullable=False),
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('eway_required', sa.Boolean(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('void_reason', sa.String(length=300), nullable=True),
    sa.Column('pdf_file_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('ISSUED', 'VOID')", name='ck_challan_status'),
    sa.ForeignKeyConstraint(['allocation_id'], ['numbering_allocation.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['challan_batch.id'], ),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['files_stored_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_id')
    )
    op.create_index(op.f('ix_challan_batch_id'), 'challan', ['batch_id'], unique=False)
    op.create_index(op.f('ix_challan_fy'), 'challan', ['fy'], unique=False)
    op.create_index(op.f('ix_challan_number'), 'challan', ['number'], unique=False)
    op.create_index(op.f('ix_challan_status'), 'challan', ['status'], unique=False)
    op.create_table('challan_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challan_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=False),
    sa.Column('hsn', sa.String(length=12), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('rate_text', sa.String(length=60), nullable=False),
    sa.Column('rate_paise', sa.BigInteger(), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['challan_id'], ['challan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challan_line_item_challan_id'), 'challan_line_item', ['challan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challan_line_item_challan_id'), table_name='challan_line_item')
    op.drop_table('challan_line_item')
    op.drop_index(op.f('ix_challan_status'), table_name='challan')
    op.drop_index(op.f('ix_challan_number'), table_name='challan')
    op.drop_index(op.f('ix_challan_fy'), table_name='challan')
    op.drop_index(op.f('ix_challan_batch_id'), table_name='challan')
    op.drop_table('challan')
    op.drop_index(op.f('ix_challan_batch_status'), table_name='challan_batch')
    op.drop_index(op.f('ix_challan_batch_created_by'), table_name='challan_batch')
    op.drop_table('challan_batch')
    # ### end Alembic commands ###
