"""consignee party golden record

Revision ID: d61ab46c13de
Revises: 690e7736007c
Create Date: 2026-08-14 13:22:59.028785
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd61ab46c13de'
down_revision: str | None = '690e7736007c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_consignee_party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address_line1', sa.String(length=300), nullable=False),
    sa.Column('address_line2', sa.String(length=300), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_md_consignee_party_gstin'), 'md_consignee_party', ['gstin'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_md_consignee_party_gstin'), table_name='md_consignee_party')
    op.drop_table('md_consignee_party')
    # ### end Alembic commands ###
