"""master data tables

Revision ID: e313362febfe
Revises: ad8a9c93c1ac
Create Date: 2026-08-10 13:55:23.046799
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e313362febfe'
down_revision: str | None = 'ad8a9c93c1ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_consignee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=600), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'state', name='uq_md_consignee_brand_state')
    )
    op.create_index(op.f('ix_md_consignee_brand'), 'md_consignee', ['brand'], unique=False)
    op.create_index(op.f('ix_md_consignee_state'), 'md_consignee', ['state'], unique=False)
    # HAND-ADDED: case-insensitive uniqueness so "Deoleo"/"deoleo"/"Deoleo " can't
    # both persist -> consignee resolution (and the GSTIN it snapshots) stays unambiguous.
    op.create_index(
        'uq_md_consignee_brand_state_ci', 'md_consignee',
        [sa.text('lower(trim(brand))'), sa.text('lower(trim(state))')], unique=True,
    )
    op.create_table('md_consignor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=600), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_md_consignor_gstin'), 'md_consignor', ['gstin'], unique=False)
    op.create_index(op.f('ix_md_consignor_name'), 'md_consignor', ['name'], unique=False)
    op.create_table('md_hsn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hsn', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_md_hsn_hsn'), 'md_hsn', ['hsn'], unique=True)
    op.create_table('md_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_md_series_letter'), 'md_series', ['letter'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_md_series_letter'), table_name='md_series')
    op.drop_table('md_series')
    op.drop_index(op.f('ix_md_hsn_hsn'), table_name='md_hsn')
    op.drop_table('md_hsn')
    op.drop_index(op.f('ix_md_consignor_name'), table_name='md_consignor')
    op.drop_index(op.f('ix_md_consignor_gstin'), table_name='md_consignor')
    op.drop_table('md_consignor')
    op.drop_index(op.f('ix_md_consignee_state'), table_name='md_consignee')
    op.drop_index(op.f('ix_md_consignee_brand'), table_name='md_consignee')
    op.drop_table('md_consignee')
    # ### end Alembic commands ###
